CREATE TABLE categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    name        VARCHAR(50) NOT NULL,
    type        VARCHAR(10) NOT NULL,
    icon_key    VARCHAR(50) NOT NULL,
    color       VARCHAR(7)  NOT NULL,
    description VARCHAR(100),
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_categories_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_categories_type
        CHECK (type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT ck_categories_color
        CHECK (color ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE UNIQUE INDEX uk_categories_user_type_name
    ON categories (user_id, type, LOWER(name));

CREATE INDEX idx_categories_user_active_type
    ON categories (user_id, active, type);

INSERT INTO categories (user_id, name, type, icon_key, color)
SELECT app_user.id, defaults.name, defaults.type, defaults.icon_key, defaults.color
FROM users app_user
CROSS JOIN (VALUES
    ('Ăn uống', 'EXPENSE', 'utensils', '#F97316'),
    ('Đi lại', 'EXPENSE', 'car', '#06B6D4'),
    ('Nhà ở', 'EXPENSE', 'home', '#3B82F6'),
    ('Hóa đơn', 'EXPENSE', 'receipt', '#EAB308'),
    ('Mua sắm', 'EXPENSE', 'shopping-bag', '#EC4899'),
    ('Giải trí', 'EXPENSE', 'film', '#8B5CF6'),
    ('Sức khỏe', 'EXPENSE', 'heart-pulse', '#EF4444'),
    ('Giáo dục', 'EXPENSE', 'graduation-cap', '#6366F1'),
    ('Quà tặng', 'EXPENSE', 'gift', '#F43F5E'),
    ('Du lịch', 'EXPENSE', 'plane', '#14B8A6'),
    ('Khác', 'EXPENSE', 'more-horizontal', '#64748B'),
    ('Lương', 'INCOME', 'briefcase', '#10B981'),
    ('Thưởng', 'INCOME', 'award', '#EAB308'),
    ('Freelance', 'INCOME', 'laptop', '#6366F1'),
    ('Kinh doanh', 'INCOME', 'wallet', '#3B82F6'),
    ('Lãi/đầu tư', 'INCOME', 'coins', '#8B5CF6'),
    ('Hoàn tiền', 'INCOME', 'sparkles', '#06B6D4'),
    ('Khác', 'INCOME', 'more-horizontal', '#64748B')
) AS defaults(name, type, icon_key, color);
