ALTER TABLE categories
    ADD CONSTRAINT uq_categories_id_user UNIQUE (id, user_id);

CREATE TABLE transactions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT         NOT NULL,
    category_id      BIGINT         NOT NULL,
    type             VARCHAR(10)    NOT NULL,
    amount           NUMERIC(18, 2) NOT NULL,
    title            VARCHAR(100)   NOT NULL,
    transaction_date DATE           NOT NULL,
    note             VARCHAR(255),
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transactions_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_transactions_category_owner
        FOREIGN KEY (category_id, user_id) REFERENCES categories (id, user_id) ON DELETE RESTRICT,
    CONSTRAINT ck_transactions_type
        CHECK (type IN ('INCOME', 'EXPENSE')),
    CONSTRAINT ck_transactions_amount_positive
        CHECK (amount > 0)
);

CREATE INDEX idx_transactions_user_date
    ON transactions (user_id, transaction_date DESC, id DESC);

CREATE INDEX idx_transactions_user_category_date
    ON transactions (user_id, category_id, transaction_date DESC);

CREATE INDEX idx_transactions_user_type_date
    ON transactions (user_id, type, transaction_date DESC);
