CREATE TABLE budgets
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL,
    category_id  BIGINT         NOT NULL,
    month        DATE           NOT NULL,
    limit_amount NUMERIC(18, 2) NOT NULL,
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_budgets_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_budgets_category_owner
        FOREIGN KEY (category_id, user_id) REFERENCES categories (id, user_id) ON DELETE RESTRICT,
    CONSTRAINT ck_budgets_month_start
        CHECK (EXTRACT(DAY FROM month) = 1),
    CONSTRAINT ck_budgets_limit_positive
        CHECK (limit_amount > 0),
    CONSTRAINT uq_budgets_user_month_category
        UNIQUE (user_id, month, category_id)
);
