ALTER TABLE categories
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE transactions
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE budgets
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE offline_operation_receipts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    operation_id  VARCHAR(36)  NOT NULL,
    entity_type   VARCHAR(20)  NOT NULL,
    local_id      VARCHAR(80),
    entity_id     BIGINT,
    entity_version BIGINT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_offline_receipts_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_offline_receipt_user_operation UNIQUE (user_id, operation_id),
    CONSTRAINT ck_offline_receipt_entity_type
        CHECK (entity_type IN ('CATEGORY', 'TRANSACTION', 'BUDGET'))
);
